import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "../components/Header";
import Feed from "../components/Feed";
import Modal from '../components/Modal'

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className="bg-gray-50 h-screen overflow-y-scroll scrollbar-none ">
      <Head>
        <title>Instagram 2.0 yunagosh</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Feed />
      <Modal />
    </div>
  );
}
